version: 0.2

phases:
  build:
    commands:
      - echo Build Starting on `date`
      - chmod +x ./mvnw
      - ./mvnw clean
      - ./mvnw package
  post_build:
    commands:
      - echo $(basename ./build/libs/*.jar)
      - pwd
artifacts:
  files:
    - '*.jar'
  base-directory: 'target'
  name: webchat

  #TODO 캐시삭제